### ISSUE TITLE
cant view products now see screen shot

### ISSUE THREAD

**Issue by feefavor1** [FeeFavor/feefavorV2#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![products1](https://user-images.githubusercontent.com/43005119/57874988-ccdda180-77df-11e9-88aa-01528994beb3.png)

**Comment by PendragonDevelopment** [comment]
The screenshot doesn't tell me anything:

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error

Expected behavior
A clear and concise description of what you expected to happen.
